
OBJS += passes/brisc/autosynth.o
OBJS += passes/brisc/getsources.o
OBJS += passes/brisc/checkinput.o
OBJS += passes/brisc/brisc.o
OBJS += passes/brisc/loadlang.o
OBJS += passes/brisc/print_ports.o
OBJS += passes/brisc/executeinst.o
OBJS += passes/brisc/executeallinsts.o
OBJS += passes/brisc/reset.o
OBJS += passes/brisc/constprop.o
