#include "kernel/register.h"
#include "kernel/celltypes.h"
#include "kernel/log.h"
#include "kernel/sigtools.h"
#include <string>
#include <sstream>
#include <set>
#include <map>

USING_YOSYS_NAMESPACE
PRIVATE_NAMESPACE_BEGIN

struct BriscBackend : public Backend {
    BriscBackend() : Backend(
            "BRISC",
            "write design to BRISC-enabled SystemVerilog file") {}

    void help() YS_OVERRIDE
    {
        log("\n");
        log("    write_brisc [filename]\n");
        log("\n");
    }

	void execute(std::ostream *&f,
                 std::string filename,
                 std::vector<std::string> args,
                 RTLIL::Design *design) YS_OVERRIDE
	{
        log_header(design, "Executing BRISC Backend.\n");

		reg_wires.clear();
		reg_ct.clear();

		reg_ct.insert("$dff");
		reg_ct.insert("$adff");
		reg_ct.insert("$dffe");
		reg_ct.insert("$dlatch");

		reg_ct.insert("$_DFF_N_");
		reg_ct.insert("$_DFF_P_");

		reg_ct.insert("$_DFF_NN0_");
		reg_ct.insert("$_DFF_NN1_");
		reg_ct.insert("$_DFF_NP0_");
		reg_ct.insert("$_DFF_NP1_");
		reg_ct.insert("$_DFF_PN0_");
		reg_ct.insert("$_DFF_PN1_");
		reg_ct.insert("$_DFF_PP0_");
		reg_ct.insert("$_DFF_PP1_");

		reg_ct.insert("$_DFFSR_NNN_");
		reg_ct.insert("$_DFFSR_NNP_");
		reg_ct.insert("$_DFFSR_NPN_");
		reg_ct.insert("$_DFFSR_NPP_");
		reg_ct.insert("$_DFFSR_PNN_");
		reg_ct.insert("$_DFFSR_PNP_");
		reg_ct.insert("$_DFFSR_PPN_");
		reg_ct.insert("$_DFFSR_PPP_");

        // Arg parsing
        size_t argidx;
        for (argidx = 1; argidx < args.size(); argidx++) {
            // Pass
            break;
        }
        extra_args(f, filename, args, argidx);

        // Here would go arg options ....

        auto p = count_cells(design);
        cell_count_comb = p.first;
        cell_count_dff = p.second;
        design->sort();

        *f << stringf("/* Generated by BRISC tool using %s */\n",
                yosys_version_str);

        log_assert(design->modules().size() == 1);

        for (Module* mod : design->modules()) {
            // No blackboxes
            if (selected && !design->selected_whole_module(mod->name)) {
                log_cmd_error("Can't handle partially selected module %s!\n",
                              mod->name.c_str());
            }
            log("Dumping module `%s'.\n", mod->name.c_str());
            dump_module(*f, "", mod);
        }

    }

    bool is_dff(const Cell* cell) const;
    std::pair<int, int> count_cells(Design* design);
    void dump_module(std::ostream& f, std::string indent, Module* mod);
    void dump_process(std::ostream&, std::string, RTLIL::Process*, bool);
    void dump_conn(std::ostream&, std::string, const SigSpec&, const SigSpec&);
    void reset_auto_counter(Module* mod);
    void reset_auto_counter_id(IdString id, bool may_rename);
    void dump_attributes(
            std::ostream& f,
            std::string indent,
            dict<IdString, Const> &attributes,
            char term='\n',
            bool modattr=false,
            bool regattr=false,
            bool as_comment=false);
    void dump_const(
            std::ostream& f,
            const Const& data,
            int width=-1,
            int offset=0,
            bool no_decimal=false,
            bool escape_comment=false);
    void dump_wire(std::ostream& f, std::string indent, Wire* wire);
    void dump_cell(std::ostream& f, std::string indent, Cell* cell);
    // bool dump_cell_expr(std::ostream& f, std::string indent, Cell* cell);
    void dump_sigspec(std::ostream &f, const SigSpec& sig);
    void dump_sigchunk(std::ostream &f, const RTLIL::SigChunk &chunk,
                       bool no_decimal=false);
    // void dump_cell_expr_port(std::ostream &f, Cell *cell, std::string port,
    //                          bool gen_signed=true);
    std::string cellname(Cell* cell);

    std::string id(IdString internal_id, bool may_rename=true);
    bool is_reg_wire(RTLIL::SigSpec sig, std::string &reg_name);
    void dump_reg_init(std::ostream& f, SigSpec sig);

    static constexpr char* comb_itf = "brisc_comb_cell_itf";
    static constexpr char* dff_itf = "brisc_dff_cell_itf";
    static constexpr char* comb_itf_id = "comb_itf";
    static constexpr char* dff_itf_id = "dff_itf";
    static constexpr bool noexpr = true;
    static constexpr bool norename = true;
    static constexpr bool defparam = false;
    bool selected = false, verbose = true, noattr=false,
         attr2comment=false, nostr=false, nodec=false, decimal=false,
         nohex=false, siminit=false;
    std::set<RTLIL::IdString> reg_wires, reg_ct;
    std::map<IdString, int> auto_name_map;
    int auto_name_counter, auto_name_offset, auto_name_digits, extmem_counter;
    std::string auto_prefix = "", extmem_prefix;
    Module* active_module;
    SigMap active_sigmap;
    dict<SigBit, State> active_initdata;
    int cell_count_dff, cell_count_comb;

	const pool<string> keywords = {
		// IEEE 1800-2017 Annex B
		"accept_on", "alias", "always", "always_comb", "always_ff",
        "always_latch", "and", "assert", "assign", "assume", "automatic",
        "before", "begin", "bind", "bins", "binsof", "bit", "break", "buf",
        "bufif0", "bufif1", "byte", "case", "casex", "casez", "cell",
        "chandle", "checker", "class", "clocking", "cmos", "config", "const",
        "constraint", "context", "continue", "cover", "covergroup",
        "coverpoint", "cross", "deassign", "default", "defparam", "design",
        "disable", "dist", "do", "edge", "else", "end", "endcase",
        "endchecker", "endclass", "endclocking", "endconfig", "endfunction",
        "endgenerate", "endgroup", "endinterface", "endmodule", "endpackage",
        "endprimitive", "endprogram", "endproperty", "endsequence",
        "endspecify", "endtable", "endtask", "enum", "event", "eventually",
        "expect", "export", "extends", "extern", "final", "first_match",
        "for", "force", "foreach", "forever", "fork", "forkjoin", "function",
        "generate", "genvar", "global", "highz0", "highz1", "if", "iff",
        "ifnone", "ignore_bins", "illegal_bins", "implements", "implies",
        "import", "incdir", "include", "initial", "inout", "input", "inside",
        "instance", "int", "integer", "interconnect", "interface",
        "intersect", "join", "join_any", "join_none", "large", "let",
        "liblist", "library", "local", "localparam", "logic", "longint",
        "macromodule", "matches", "medium", "modport", "module", "nand",
        "negedge", "nettype", "new", "nexttime", "nmos", "nor",
        "noshowcancelled", "not", "notif0", "notif1", "null", "or", "output",
        "package", "packed", "parameter", "pmos", "posedge", "primitive",
        "priority", "program", "property", "protected", "pull0", "pull1",
        "pulldown", "pullup", "pulsestyle_ondetect", "pulsestyle_onevent",
        "pure", "rand", "randc", "randcase", "randsequence", "rcmos", "real",
        "realtime", "ref", "reg", "reject_on", "release", "repeat",
        "restrict", "return", "rnmos", "rpmos", "rtran", "rtranif0",
        "rtranif1", "s_always", "s_eventually", "s_nexttime", "s_until",
        "s_until_with", "scalared", "sequence", "shortint", "shortreal",
        "showcancelled", "signed", "small", "soft", "solve", "specify",
        "specparam", "static", "string", "strong", "strong0", "strong1",
        "struct", "super", "supply0", "supply1", "sync_accept_on",
        "sync_reject_on", "table", "tagged", "task", "this", "throughout",
        "time", "timeprecision", "timeunit", "tran", "tranif0", "tranif1",
        "tri", "tri0", "tri1", "triand", "trior", "trireg", "type", "typedef",
        "union", "unique", "unique0", "unsigned", "until", "until_with",
        "untyped", "use", "uwire", "var", "vectored", "virtual", "void",
        "wait", "wait_order", "wand", "weak", "weak0", "weak1", "while",
        "wildcard", "wire", "with", "within", "wor", "xnor", "xor"};


} BriscBackend;


bool
BriscBackend::is_dff(const Cell* cell) const
{
    return reg_ct.count(cell->type) && cell->hasPort("\\Q");
}

/// @brief Count comb / dff cells in design's top_module
/// @return <comb count, dff count>
std::pair<int, int>
BriscBackend::count_cells(Design* design)
{
    int comb = 0, dff = 0;

    for (Cell* cell : design->top_module()->cells()) {
        if (nullptr == cell)
            continue;
        if (is_dff(cell)) {
            ++dff;
        }
        else {
            ++comb;
        }
    }
    return make_pair(comb, dff);
}

void
BriscBackend::
dump_module(std::ostream& f, std::string indent, Module* mod)
{
    reg_wires.clear();
    reset_auto_counter(mod);
    active_module = mod;
    active_sigmap.set(active_module);
    active_initdata.clear();

    // Get initializaton information
    for (auto wire : mod->wires()) {
        if (wire->attributes.count("\\init")) {
            SigSpec sig = active_sigmap(wire);
            Const val = wire->attributes.at("\\init");
            for (int i = 0; i < GetSize(sig) && i < GetSize(val); i++) {
                if (val[i] == State::S0 || val[i] == State::S1) {
                    active_initdata[sig[i]] = val[i];
                }
            }
        }
    }

    // Check for processes
    if (mod->has_processes()) {
		log_warning("Module %s contains unmapped RTLIL processes. RTLIL processes\n"
				"can't always be mapped directly to Verilog always blocks. Unintended\n"
				"changes in simulation behavior are possible! Use \"proc\" to convert\n"
				"processes to logic networks and registers.\n", log_id(mod));
        log_abort();
    }

    // Dump processes
    f << stringf("\n");
	// for (auto it = mod->processes.begin(); it != mod->processes.end(); ++it) {
	// 	dump_process(f, indent + "  ", it->second, true);
    // }

    /// Impossible to reach --- noexpr is static constexpr true
    if (!noexpr) {
        log_abort();
    }

    dump_attributes(f, indent, mod->attributes, '\n', /*modattr=*/true);
    f << stringf("%s" "module %s\n(", indent.c_str(),
                 id(mod->name, false).c_str());

    // Dump input / output ports
    bool keep_running = true;
    static constexpr char _inport[] = "input ";
    static constexpr char _outport[] = "output logic ";
    for (int port_id = 1; keep_running; port_id++) {
        keep_running = false;
        for (Wire* wire : mod->wires()) {
            if (wire->port_id == port_id) {
                if (port_id != 1) {
                    f << stringf(",");
                }
                std::string range = "";
                if (wire->width != 1) {
                    if (wire->upto) {
                        range = stringf("[%d:%d]", wire->start_offset,
                                        wire->width-1 + wire->start_offset);
                    }
                    else {
                        range = stringf("[%d:%d]",
                                        wire->width-1 + wire->start_offset,
                                        wire->start_offset);
                    }
                }
                f << stringf("\n%s  %s %s %s"
                        ,indent.c_str()
                        ,wire->port_input && wire->port_output ?
                                                   "inout logic " :
                            wire->port_input  ?              _inport :
                            wire->port_output ?             _outport :
                                  "error --- unknown port direction"
                        ,range.c_str()
                        ,id(wire->name).c_str());
                keep_running = true;
                continue;
            }
        }
    }

    // Dump interface ports
    f << stringf("\n%s  ,%s._cell %s [%d]"
                 ,indent.c_str()
                 ,comb_itf
                 ,comb_itf_id
                 ,cell_count_comb
                 );
    f << stringf("\n%s  ,%s._cell %s [%d]"
                 ,indent.c_str()
                 ,dff_itf
                 ,dff_itf_id
                 ,cell_count_dff
                 );
	f << stringf("%s\n);\n", indent.c_str());

    for (auto wire : mod->wires()) {
        if (wire->port_input || wire->port_output)
            continue;
        dump_wire(f, indent + "  ", wire);
    }

    for (auto it = mod->memories.begin(); it != mod->memories.end(); ++it) {
        log_error("BRISC does not support memories...\n");
        log_abort();
    }

    for (Cell* cell : mod->cells()) {
        dump_cell(f, indent + " ", cell);
    }

    for (auto conn : mod->connections()) {
        dump_conn(f, indent + "  ", conn.first, conn.second);
    }

	f << stringf("%s" "endmodule\n", indent.c_str());
	active_module = NULL;
	active_sigmap.clear();
	active_initdata.clear();
}

void
BriscBackend::reset_auto_counter(Module *mod)
{
    auto_name_map.clear();
    auto_name_counter = auto_name_offset = 0;

    reset_auto_counter_id(mod->name, false);

    for (Wire* wire : mod->wires()) {
        reset_auto_counter_id(wire->name, true);
    }

    for (Cell* cell : mod->cells()) {
        reset_auto_counter_id(cell->name, true);
        reset_auto_counter_id(cell->type, false);
    }

    log_assert(!mod->has_processes());
    // Boilerplate anyway
	for (auto it = mod->processes.begin(); it != mod->processes.end(); ++it) {
		reset_auto_counter_id(it->second->name, false);
    }

    auto_name_digits = 1;
    for (size_t i = 10; i < auto_name_offset + auto_name_map.size(); i *= 10) {
        auto_name_digits++;
    }

    if (verbose) {
        for (auto it : auto_name_map) {
            log("  renaming `%s' to `%s_%0*d_'.\n", it.first.c_str(),
                    auto_prefix.c_str(),
                    auto_name_digits, auto_name_offset + it.second);
        }
    }
}

void
BriscBackend::reset_auto_counter_id(IdString id, bool may_rename)
{
    const char* str = id.c_str();

    if constexpr (!norename) {
        if (str[0] == '$' && may_rename && !norename) {
            auto_name_map[id] = auto_name_counter++;
        }
        log_abort();
    }

    if (str[0] != '\\' || str[1] != '_' || str[2] == '\0') {
        return;
    }

    for (int i = 2; str[i] != '\0'; ++i) {
        if (str[i] == '_' && str[i+1] == '\0') {
            continue;
        }
        if (str[i] < '0' || str[i] > '9')
            return;
    }

    int num = atoi(str+2);
    if (num >= auto_name_offset)
        auto_name_offset = num + 1;
}

void
BriscBackend::dump_process(std::ostream&, std::string, RTLIL::Process*, bool)
{
    log_error("BRISC Must not have processes\n");
    log_abort();
}


void
BriscBackend::dump_attributes(
        std::ostream& f,
        std::string indent,
        dict<IdString, Const> &attributes,
        char term,
        bool modattr,
        bool regattr,
        bool as_comment)
{
    if (noattr)
        return;
    as_comment |= attr2comment;

    for (auto it : attributes) {
        if (it.first == "\\init" && regattr)
            continue;

        f << stringf("%s" "%s %s", indent.c_str(), as_comment ? "/*" : "(*",
                id(it.first).c_str());
        f << stringf(" = ");
        if (modattr && (it.second == State::S0 || it.second == Const(0))) {
            f << stringf( " 0 ");
        }
        else if (modattr && (it.second == State::S1 || it.second == Const(0))) {
            f << stringf(" 1 ");
        }
        else {
            dump_const(f, it.second, -1, 0, false, as_comment);
        }
        f << stringf(" %s%c", as_comment ? "*/" : "*)", term);
    }

}

std::string
BriscBackend::id(IdString internal_id, bool may_rename)
{
    const char* str = internal_id.c_str();
    bool do_escape = false;

    if (may_rename && auto_name_map.count(internal_id) != 0) {
        return stringf("%s_%0*d_", auto_prefix.c_str(), auto_name_digits,
                auto_name_offset + auto_name_map[internal_id]);
    }

    if (*str == '\\')
        str++;

    if ('0' <= *str && *str <= '9')
        do_escape = true;

    for (int i = 0; str[i] != '\0'; ++i) {
        if ('0' <= *str && *str <= '9')
            continue;
		if ('a' <= str[i] && str[i] <= 'z')
			continue;
		if ('A' <= str[i] && str[i] <= 'Z')
			continue;
		if (str[i] == '_')
			continue;
        do_escape = true;
        break;
    }

    if (keywords.count(str))
        do_escape = true;

    if (do_escape)
        return "\\" + std::string(str) + " ";
    return std::string(str);
}

void
BriscBackend::dump_const(
        std::ostream& f,
        const Const& data,
        int width,
        int offset,
        bool no_decimal,
        bool escape_comment)
{
    bool set_signed = (data.flags & RTLIL::CONST_FLAG_SIGNED);

    if (width < 0)
        width = data.bits.size() - offset;
    if (width == 0) {
		// See IEEE 1364-2005 Clause 5.1.14.
		f << "{0{1'b0}}";
		return;
	}
    
    if (nostr) {
        goto dump_hex;
    }

    if ((data.flags & RTLIL::CONST_FLAG_STRING) == 0 ||
            width != (int)data.bits.size()) {
        if (width == 32 && !no_decimal && !nodec) {
            int32_t val = 0;
            for (int i = offset+width-1; i >= offset; i--) {
				log_assert(i < (int)data.bits.size());
				if (data.bits[i] != State::S0 && data.bits[i] != State::S1)
					goto dump_hex;
				if (data.bits[i] == State::S1)
					val |= 1 << (i - offset);
            }
            if (decimal) {
                f << stringf("%d", val);
            }
            else if (set_signed && val < 0) {
                f << stringf("-32'sd%u", -val);
            }
            else {
                f << stringf("32'%sd%u", set_signed ? "s" : "", val);
            }
        }
        else {
dump_hex:
            if (nohex) {
                goto dump_bin;
            }
            vector<char> bin_digits, hex_digits;
            for (int i = offset; i < offset+width; ++i) {
                log_assert(i < (int)data.bits.size());
                switch (data.bits[i]) {
                    case State::S0: bin_digits.push_back('0'); break;
                    case State::S1: bin_digits.push_back('1'); break;
                    case State::Sx: bin_digits.push_back('x'); break;
                    case State::Sz: bin_digits.push_back('z'); break;
                    case State::Sa: bin_digits.push_back('?'); break;
                    case State::Sm:
                        log_error("Found marker state in final netlist");
                }
            }

			if (GetSize(bin_digits) == 0) {
				goto dump_bin;
            }

			while (GetSize(bin_digits) % 4 != 0) {
				if (bin_digits.back() == '1') {
					bin_digits.push_back('0');
                }
				else {
					bin_digits.push_back(bin_digits.back());
                }
            }

            for (int i = 0; i < GetSize(bin_digits); i+= 4)
            {
				char bit_3 = bin_digits[i+3];
				char bit_2 = bin_digits[i+2];
				char bit_1 = bin_digits[i+1];
				char bit_0 = bin_digits[i+0];
				if (bit_3 == 'x' || bit_2 == 'x' || bit_1 == 'x' ||bit_0 == 'x') {
					if (bit_3 != 'x' || bit_2 != 'x' || bit_1 != 'x' || bit_0 != 'x')
						goto dump_bin;
					hex_digits.push_back('x');
					continue;
				}
				if (bit_3 == 'z' || bit_2 == 'z' || bit_1 == 'z' || bit_0 == 'z') {
					if (bit_3 != 'z' || bit_2 != 'z' || bit_1 != 'z' || bit_0 != 'z')
						goto dump_bin;
					hex_digits.push_back('z');
					continue;
				}
				if (bit_3 == '?' || bit_2 == '?' || bit_1 == '?' || bit_0 == '?') {
					if (bit_3 != '?' || bit_2 != '?' || bit_1 != '?' || bit_0 != '?')
						goto dump_bin;
					hex_digits.push_back('?');
					continue;
				}
				int val = 8*(bit_3 - '0') + 4*(bit_2 - '0') + 2*(bit_1 - '0') +
                            (bit_0 - '0');
				hex_digits.push_back(val < 10 ? '0' + val : 'a' + val - 10);
            }

			f << stringf("%d'%sh", width, set_signed ? "s" : "");
			for (int i = GetSize(hex_digits)-1; i >= 0; i--) {
				f << hex_digits[i];
            }
        }

		if (0) {
	dump_bin:
			f << stringf("%d'%sb", width, set_signed ? "s" : "");
			if (width == 0)
				f << stringf("0");
			for (int i = offset+width-1; i >= offset; i--) {
				log_assert(i < (int)data.bits.size());
				switch (data.bits[i]) {
				case State::S0: f << stringf("0"); break;
				case State::S1: f << stringf("1"); break;
				case RTLIL::Sx: f << stringf("x"); break;
				case RTLIL::Sz: f << stringf("z"); break;
				case RTLIL::Sa: f << stringf("?"); break;
				case RTLIL::Sm: log_error("Found marker state in final netlist.");
				}
			}
		}
    }
    else {
		if ((data.flags & RTLIL::CONST_FLAG_REAL) == 0)
			f << stringf("\"");
		std::string str = data.decode_string();
		for (size_t i = 0; i < str.size(); i++) {
			if (str[i] == '\n')
				f << stringf("\\n");
			else if (str[i] == '\t')
				f << stringf("\\t");
			else if (str[i] < 32)
				f << stringf("\\%03o", str[i]);
			else if (str[i] == '"')
				f << stringf("\\\"");
			else if (str[i] == '\\')
				f << stringf("\\\\");
			else if (str[i] == '/' && escape_comment && i > 0 && str[i-1] == '*')
				f << stringf("\\/");
			else
				f << str[i];
		}
		if ((data.flags & RTLIL::CONST_FLAG_REAL) == 0)
			f << stringf("\"");
    }
}

void
BriscBackend::dump_wire(std::ostream& f, std::string indent, Wire* wire)
{
    dump_attributes(f, indent, wire->attributes, '\n',
            /*modattr=*/false, /*regattr=*/reg_wires.count(wire->name));

    std::string range = "";
    if (wire->width != 1) {
        if (wire->upto) {
			range = stringf(" [%d:%d]", wire->start_offset,
                    wire->width - 1 + wire->start_offset);
        }
        else {
			range = stringf(" [%d:%d]", wire->width - 1 + wire->start_offset,
                    wire->start_offset);
        }
    }
	if (wire->port_input && !wire->port_output) {
		f << stringf("%s" "input%s %s;\n", indent.c_str(), range.c_str(),
                     id(wire->name).c_str());
    }
	if (!wire->port_input && wire->port_output) {
		f << stringf("%s" "output%s %s;\n", indent.c_str(), range.c_str(),
                     id(wire->name).c_str());
    }
	if (wire->port_input && wire->port_output) {
		f << stringf("%s" "inout%s %s;\n", indent.c_str(), range.c_str(),
                     id(wire->name).c_str());
    }
	if (reg_wires.count(wire->name)) {
		f << stringf("%s" "reg%s %s", indent.c_str(), range.c_str(),
                     id(wire->name).c_str());
		if (wire->attributes.count("\\init")) {
			f << stringf(" = ");
			dump_const(f, wire->attributes.at("\\init"));
		}
		f << stringf(";\n");
	}
    else if (!wire->port_input && !wire->port_output) {
		f << stringf("%s" "wire%s %s;\n", indent.c_str(), range.c_str(), id(wire->name).c_str());
    }
}

void
BriscBackend::dump_cell(std::ostream& f, std::string indent, Cell* cell)
{
	if (cell->type[0] == '$' && !noexpr) {
        log_abort(); // Impossible to hit
		// if (dump_cell_expr(f, indent, cell))
		// 	return;
	}
	dump_attributes(f, indent, cell->attributes);
	f << stringf("%s" "%s", indent.c_str(),
                 id(cell->type, /*mayrename*/ false).c_str());

    if (!defparam && cell->parameters.size() > 0) {
        log_error("Expected Zero parameters\n");
        log_error("To implement, see verilog_backend.cc:dump_cell\n");
        log_abort();
    }

    std::string cell_name = cellname(cell);
	if (cell_name != id(cell->name))
		f << stringf(" %s /* %s */ (", cell_name.c_str(), id(cell->name).c_str());
	else
		f << stringf(" %s (", cell_name.c_str());

    // Write Ports
	bool first_arg = true;
	std::set<RTLIL::IdString> numbered_ports;
	for (int i = 1; true; i++) {
		char str[16];
		snprintf(str, 16, "$%d", i);
		for (auto it = cell->connections().begin(); it != cell->connections().end(); ++it) {
			if (it->first != str)
				continue;
			if (!first_arg)
				f << stringf(",");
			first_arg = false;
			f << stringf("\n%s  ", indent.c_str());
			dump_sigspec(f, it->second);
			numbered_ports.insert(it->first);
			goto found_numbered_port;
		}
		break;
	found_numbered_port:;
	}
	for (auto it = cell->connections().begin(); it != cell->connections().end(); ++it) {
		if (numbered_ports.count(it->first))
			continue;
		if (!first_arg)
			f << stringf(",");
		first_arg = false;
		f << stringf("\n%s  .%s(", indent.c_str(), id(it->first).c_str());
		if (it->second.size() > 0)
			dump_sigspec(f, it->second);
		f << stringf(")");
	}

    // Write interface ports
    static int comb_offset = 0;
    static int dff_offset = 0;
    bool dff = is_dff(cell);
    f << stringf(",\n%s  ", indent.c_str());
    f << stringf(".itf(%s[%d])",
            dff ? dff_itf_id : comb_itf_id,
            dff ? dff_offset++ : comb_offset++); // Note: Ternary operator is correct
    f << stringf("\n%s);\n", indent.c_str());

	if constexpr (defparam) {
        log_abort();
	}

	if (siminit && reg_ct.count(cell->type) && cell->hasPort("\\Q")) {
		std::stringstream ss;
		dump_reg_init(ss, cell->getPort("\\Q"));
		if (!ss.str().empty()) {
			f << stringf("%sinitial %s.Q", indent.c_str(), cell_name.c_str());
			f << ss.str();
			f << ";\n";
		}
	}

}

void
BriscBackend::dump_sigspec(std::ostream &f, const RTLIL::SigSpec &sig)
{
	if (GetSize(sig) == 0) {
		f << "\"\"";
		return;
	}
	if (sig.is_chunk()) {
		dump_sigchunk(f, sig.as_chunk());
	} else {
		f << stringf("{ ");
		for (auto it = sig.chunks().rbegin(); it != sig.chunks().rend(); ++it) {
			if (it != sig.chunks().rbegin())
				f << stringf(", ");
			dump_sigchunk(f, *it, true);
		}
		f << stringf(" }");
	}
}

void
BriscBackend::dump_sigchunk(std::ostream &f, const RTLIL::SigChunk &chunk,
                            bool no_decimal)
{
    // If Const
    if (chunk.wire == nullptr) {
		dump_const(f, chunk.data, chunk.width, chunk.offset, no_decimal);
        return;
    }

    if (chunk.width == chunk.wire->width && chunk.offset == 0) {
        f << stringf("%s", id(chunk.wire->name).c_str());
    }
    else if (chunk.width == 1) {
        if (chunk.wire->upto) {
            f << stringf("%s[%d]", id(chunk.wire->name).c_str(),
                        (chunk.wire->width - chunk.offset - 1) +
                        chunk.wire->start_offset);
        }
        else {
            f << stringf("%s[%d]", id(chunk.wire->name).c_str(),
                         chunk.offset + chunk.wire->start_offset);
        }
    }
    else {
        if (chunk.wire->upto) {
            f << stringf(
                    "%s[%d:%d]", id(chunk.wire->name).c_str(),
                    (chunk.wire->width - (chunk.offset + chunk.width - 1) - 1)+
                    chunk.wire->start_offset,
                    (chunk.wire->width - chunk.offset - 1) +
                    chunk.wire->start_offset
                    );
        }
        else
            f << stringf(
                    "%s[%d:%d]", id(chunk.wire->name).c_str(),
                    (chunk.offset + chunk.width - 1) + chunk.wire->start_offset,
                    chunk.offset + chunk.wire->start_offset
                    );
    }

}

std::string
BriscBackend::cellname(Cell* cell)
{
    if constexpr (!norename) {
        log_abort();
    }
	else
	{
// no_special_reg_name:
		return id(cell->name).c_str();
	}
}

bool
BriscBackend::is_reg_wire(RTLIL::SigSpec sig, std::string &reg_name)
{
	if (!sig.is_chunk() || sig.as_chunk().wire == NULL)
		return false;

	RTLIL::SigChunk chunk = sig.as_chunk();

	if (reg_wires.count(chunk.wire->name) == 0)
		return false;

	reg_name = id(chunk.wire->name);

	if (sig.size() != chunk.wire->width) {
		if (sig.size() == 1) {
			reg_name += stringf("[%d]",
                                chunk.wire->start_offset +  chunk.offset);
        }
		else if (chunk.wire->upto) {
			reg_name += stringf("[%d:%d]",
                    (chunk.wire->width - (chunk.offset + chunk.width - 1) - 1) +
                        chunk.wire->start_offset,
					(chunk.wire->width - chunk.offset - 1) +
                        chunk.wire->start_offset);
        }
		else {
			reg_name += stringf("[%d:%d]",
                                chunk.wire->start_offset +
                                    chunk.offset + chunk.width - 1,
					            chunk.wire->start_offset +  chunk.offset);
        }
	}

	return true;
}

void
BriscBackend::dump_reg_init(std::ostream& f, SigSpec sig)
{
    Const initval;
    bool gotinit = false;

    for (auto bit : active_sigmap(sig)) {
        if (active_initdata.count(bit)) {
            initval.bits.push_back(active_initdata.at(bit));
            gotinit = true;
        }
        else {
            initval.bits.push_back(State::Sx);
        }
    }

    if (gotinit) {
        f << " = ";
        dump_const(f, initval);
    }
}

void
BriscBackend::dump_conn(
        std::ostream& f,
        std::string indent,
        const SigSpec& left,
        const SigSpec& right)
{
	f << stringf("%s" "assign ", indent.c_str());
	dump_sigspec(f, left);
	f << stringf(" = ");
	dump_sigspec(f, right);
	f << stringf(";\n");
}


PRIVATE_NAMESPACE_END
